const oracledb = require('oracledb');
const fs = require('fs');
const path = require('path');

const envPath = path.resolve(process.cwd(), '.env.local');
if (fs.existsSync(envPath)) {
    const envConfig = fs.readFileSync(envPath, 'utf8');
    envConfig.split('\n').forEach(line => {
        const parts = line.split('=');
        if (parts.length === 2) {
            process.env[parts[0].trim()] = parts[1].trim();
        }
    });
}

async function run() {
    let connection;
    try {
        console.log('Connecting to Oracle...');
        connection = await oracledb.getConnection({
            user: process.env.ORACLE_USER,
            password: process.env.ORACLE_PASSWORD,
            connectionString: process.env.ORACLE_CONNECTION_STRING
        });
        console.log('Connected.');

        const result = await connection.execute('SELECT table_name FROM user_tables WHERE table_name LIKE \'DIGI_%\'');
        console.log('DIGI tables:', result.rows);

        // Check DIGI_AUDIT_LOGS
        const auditExist = result.rows.some(r => r[0] === 'DIGI_AUDIT_LOGS' || r.TABLE_NAME === 'DIGI_AUDIT_LOGS');
        if (!auditExist) {
            console.log('Creating DIGI_AUDIT_LOGS...');
            await connection.execute(`
                CREATE TABLE DIGI_AUDIT_LOGS (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    user_name VARCHAR2(255),
                    action VARCHAR2(50),
                    entity_type VARCHAR2(50),
                    entity_id VARCHAR2(255),
                    description VARCHAR2(4000)
                )
            `);
            console.log('DIGI_AUDIT_LOGS created.');
        } else {
            console.log('DIGI_AUDIT_LOGS already exists.');
        }

        await connection.commit();
    } catch (err) {
        console.error('Error:', err.message);
    } finally {
        if (connection) await connection.close();
    }
}
run();
